services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000" # Mapea el puerto 3000 del host al puerto 3000 del contenedor

    restart: unless-stopped
    depends_on: [mysql]

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306" # Usar la variable MYSQL_PORT para el puerto externo
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d

volumes:
  db_data:
